### PR TITLE
Oauth2 and basic opds2 authentication

### PR DESCRIPTION
**Pull request by panaC**

### CODE REVIEW

**Comment by panaC** [comment]
ready to merge @danielweck

**Comment by danielweck** [comment]
Hello @panaC there is a minor merge conflict to solve in this PR. Once you have resolved it, could you please let me know if you are still okay to merge this PR? It looks good to me, but I need to double-check with you since some time has passed since, and you have built other features in other PRs. Thanks!

**Comment by danielweck** [comment]
Compile error:

```
    ERROR in src/renderer/library/components/opds/Auth.tsx
    TS1208: 'Auth.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
```

**Comment by danielweck** [comment]
To solve the compile error:
`git rm src/renderer/library/components/opds/Auth.tsx`

**Pull request merged**
