### PR TITLE
[WIP] lcpl end date expired 32bit timestamp

### LINKED ISSUE #1355: lcpl: expired licence when end date over 2050
https://github.com/edrlab/thorium-reader/blob/cf04170d65959b66cef906f3cbe362d8dbbd73c0/src/main/redux/sagas/api/publication/import/importLcplFromFs.ts#L67-L69

### PR DESCRIPTION
**Pull request by panaC**
fixes #1355

### CODE REVIEW

**Comment by danielweck** [comment]
Mhmm, Moment works fine, it is the C/C++ code that fails.

**Comment by panaC** [comment]
yeap . you're right moment works fine.

**Comment by danielweck** [comment]
After spending some time diffing files manually, I found the exact `date.h` used in LCP lib:
https://github.com/HowardHinnant/date/blob/3c3ba6890648b7c4adcfdf082a4c3803d22f5a21/include/date/date.h

Code diff with their `master` branch:
https://github.com/HowardHinnant/date/compare/3c3ba6890648b7c4adcfdf082a4c3803d22f5a21...master#diff-0b69f38c40f39535998f884bf75dab9500e3d9a7cfa977d60111fac7f4005d52

**Comment by danielweck** [comment]
I found this reference to `2038`: https://github.com/HowardHinnant/date/issues/397#issuecomment-426024220

**Comment by panaC** [comment]
I'm closing the PR , may you track your progress in the issue @danielweck

**Pull request closed without merging**
