### PR TITLE
Request for adding Chinese UI translation

### PR DESCRIPTION
**Pull request by maitreya2019**
Hi there, I'm a chinese user and love this software very much. Thorium is just THE perfect ebook reader for me. I am very willing to contribute to the project, so I creat the simplified chinese UI translation file (zh-cn.json) which has passed all the i18n tests in my local repoitory, alongside chinese locale name file (zhCnLang.json) and information file (zh-cn.md). I'm just a newcomer in Github and hope this small work could do some help. Best wishes!

### CODE REVIEW

**Comment by panaC** [comment]
Amazing,
Thank you very much 👍

**Comment by maitreya2019** [comment]
@panaC You are welcome! Hope I could do more for the project:)

**Comment by danielweck** [comment]
Hello, I am merging your work into a intermediary branch, so that a few integration issues can be fixed. I will let you know when your work is merged into the develop branch.

**Comment by danielweck** [comment]
All done 👍 https://github.com/edrlab/thorium-reader/pull/1306
Thank you very much! :)

**Comment by maitreya2019** [comment]
You are welcome! Anything for the project! :)

**Pull request merged**
