### PR TITLE
LSD migration from r2-lcp-js/lsd

### PR DESCRIPTION
**Pull request by panaC**

### CODE REVIEW

**Comment by danielweck** [comment]
Hello Pierre, looks good so far! Thanks. Have you tested the LCP/LSD network interactions already? => initial register (make sure Thorium only calls once, and details appear in LSD JSON record), renew and return from client side, and also revoke from server side ... maybe try server errors too but I am not sure how to do this easily without modifying the Go server source code.

**Comment by panaC** [comment]
Test with an lcp publication created from edrlab front-prod : alice 

1/ import in thorium : 
```
readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/lcpserver/contents/19106a1e-676b-42cd-a6f5-cfd58f1d3ea2 +0ms
```
2/ fetch lsd license 
```
[2]   readium-desktop:main#services/lsd Link Status FOUND:  Link {
[2]   Href: 'https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/status',
[2]   Type: 'application/vnd.readium.license.status.v1.0+json',
[2]   Rel: 'status'
[2] } +0ms
readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/status
```
3/ register license
```
[2]   readium-desktop:main#services/lsd REGISTER: https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/register?id=93933c79-79ba-4896-a6f5-b018f242915f&name=Thorium +157ms
[2]   readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/register?id=93933c79-79ba-4896-a6f5-b018f242915f&name=Thorium +129ms
```
4/ registered response
```
[2]   readium-desktop:main#services/lsd registered response : +130ms
[2]   readium-desktop:main#services/lsd LSD {
[2]   readium-desktop:main#services/lsd   ID: '4e4672ad-b411-481f-b53e-6e78b49ee327',
[2]   readium-desktop:main#services/lsd   Status: 'active',
[2]   readium-desktop:main#services/lsd   Message: 'The license is in active state',
[2]   readium-desktop:main#services/lsd   Updated: Updated {
[2]   readium-desktop:main#services/lsd     License: 2024-05-01T17:16:52.000Z,
[2]   readium-desktop:main#services/lsd     Status: 2024-05-01T17:20:07.000Z
[2]   readium-desktop:main#services/lsd   },
[2]   readium-desktop:main#services/lsd   Links: [
[2]   readium-desktop:main#services/lsd     Link {
[2]   readium-desktop:main#services/lsd       Href: 'https://front-prod.edrlab.org/frontend/api/v1/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327',
[2]   readium-desktop:main#services/lsd       Type: 'application/vnd.readium.lcp.license.v1.0+json',
[2]   readium-desktop:main#services/lsd       Rel: 'license'
[2]   readium-desktop:main#services/lsd     },
[2]   readium-desktop:main#services/lsd     Link {
[2]   readium-desktop:main#services/lsd       Href: 'https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/register{?id,name}',
[2]   readium-desktop:main#services/lsd       Type: 'application/vnd.readium.license.status.v1.0+json',
[2]   readium-desktop:main#services/lsd       Templated: true,
[2]   readium-desktop:main#services/lsd       Rel: 'register'
[2]   readium-desktop:main#services/lsd     }
[2]   readium-desktop:main#services/lsd   ],
[2]   readium-desktop:main#services/lsd   Events: [
[2]   readium-desktop:main#services/lsd     LsdEvent {
[2]   readium-desktop:main#services/lsd       Type: 'register',
[2]   readium-desktop:main#services/lsd       Name: 'Thorium',
[2]   readium-desktop:main#services/lsd       ID: '93933c79-79ba-4896-a6f5-b018f242915f',
[2]   readium-desktop:main#services/lsd       TimeStamp: 2024-05-01T17:20:07.000Z
[2]   readium-desktop:main#services/lsd     }
[2]   readium-desktop:main#services/lsd   ]
[2]   readium-desktop:main#services/lsd } +0ms
```
5/ status document procedure done
```
[2]   readium-desktop:main#services/lcp launchStatusDocumentProcessing DONE. +14s
```

----

Now I open the publication : 

1/ fetch the lsd license
```
[2]   Href: 'https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/status',
[2]   Type: 'application/vnd.readium.license.status.v1.0+json',
[2]   Rel: 'status'
[2] } +7m
[2]   readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/status +7m
```
2/ no need to lsd register because already done in the first import
```
[2]   readium-desktop:main#services/lsd No need to LSD register. +263ms
```

3/ cannot found the passphrase
```
[2]   r2:lcp#parser/epub/lcp findOneValidPassphrase ERROR +0ms
```

My passphrase is `pierre`

4/ refresh the lsd license
```
[2]   readium-desktop:main#services/lsd Link Status FOUND:  Link {
[2]   Href: 'https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/status',
[2]   Type: 'application/vnd.readium.license.status.v1.0+json',
[2]   Rel: 'status'
[2] } +3m
[2]   readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/lsdserver/licenses/4e4672ad-b411-481f-b53e-6e78b49ee327/status +3m
```

**Comment by panaC** [comment]
Test with a "Loan" publication : 

image

Renew : 

image

```
[2]   readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/lsdserver/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6/renew?id=93933c79-79ba-4896-a6f5-b018f242915f&name=Thorium +188ms
[2]   readium-desktop:main/http Response URL: https://front-prod.edrlab.org/lsdserver/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6/renew?id=93933c79-79ba-4896-a6f5-b018f242915f&name=Thorium +0ms
[2]   readium-desktop:main/http Method put +0ms
[2]   readium-desktop:main/http Request headers : +0ms
[2]   readium-desktop:main/http {
[2]   readium-desktop:main/http   'accept-language': 'fr,en-US;q=0.7,en;q=0.5',
[2]   readium-desktop:main/http   'user-agent': 'readium-desktop'
[2]   readium-desktop:main/http } +0ms
[2]   readium-desktop:main/http ### +0ms
[2]   readium-desktop:main/http OK:  false +0ms
[2]   readium-desktop:main/http status code : 403 +0ms
[2]   readium-desktop:main/http status text : Forbidden +0ms
[2]   readium-desktop:main/http Response headers : +0ms
[2]   readium-desktop:main/http {
[2]   readium-desktop:main/http   'alt-svc': [ 'h3=":443"; ma=2592000' ],
[2]   readium-desktop:main/http   connection: [ 'close' ],
[2]   readium-desktop:main/http   'content-length': [ '201' ],
[2]   readium-desktop:main/http   'content-type': [ 'application/problem+json' ],
[2]   readium-desktop:main/http   date: [ 'Wed, 01 May 2024 17:46:10 GMT' ],
[2]   readium-desktop:main/http   server: [ 'Caddy', 'nginx/1.24.0' ],
[2]   readium-desktop:main/http   vary: [ 'Origin' ],
[2]   readium-desktop:main/http   'x-content-type-options': [ 'nosniff' ]
[2]   readium-desktop:main/http } +0ms
[2]   readium-desktop:main/http ### +0ms
[2]   readium-desktop:main#services/lcp Forbidden (Attempt to renew with a date greater than potential rights end = 2026-05-04T17:42:00Z) [http://readium.org/license-status-document/error/renew/date|403] +187ms
```

Return : 

image

```
[2]   readium-desktop:main#services/lsd RETURN: https://front-prod.edrlab.org/lsdserver/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6/return?id=93933c79-79ba-4896-a6f5-b018f242915f&name=Thorium +7ms
```

```
[2]   readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/lsdserver/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6/return?id=93933c79-79ba-4896-a6f5-b018f242915f&name=Thorium +691ms
[2]   readium-desktop:main/http Response URL: https://front-prod.edrlab.org/lsdserver/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6/return?id=93933c79-79ba-4896-a6f5-b018f242915f&name=Thorium +0ms
[2]   readium-desktop:main/http Method put +0ms
[2]   readium-desktop:main/http Request headers : +0ms
[2]   readium-desktop:main/http {
[2]   readium-desktop:main/http   'accept-language': 'fr,en-US;q=0.7,en;q=0.5',
[2]   readium-desktop:main/http   'user-agent': 'readium-desktop'
[2]   readium-desktop:main/http } +0ms
[2]   readium-desktop:main/http ### +0ms
[2]   readium-desktop:main/http OK:  true +0ms
[2]   readium-desktop:main/http status code : 200 +0ms
[2]   readium-desktop:main/http status text : OK +0ms
[2]   readium-desktop:main/http Response headers : +0ms
[2]   readium-desktop:main/http {
[2]   readium-desktop:main/http   'alt-svc': [ 'h3=":443"; ma=2592000' ],
[2]   readium-desktop:main/http   connection: [ 'close' ],
[2]   readium-desktop:main/http   'content-length': [ '663' ],
[2]   readium-desktop:main/http   'content-type': [ 'application/vnd.readium.license.status.v1.0+json' ],
[2]   readium-desktop:main/http   date: [ 'Wed, 01 May 2024 17:47:16 GMT' ],
[2]   readium-desktop:main/http   server: [ 'Caddy', 'nginx/1.24.0' ],
[2]   readium-desktop:main/http   vary: [ 'Origin' ]
[2]   readium-desktop:main/http } +0ms
[2]   readium-desktop:main/http ### +0ms
[2]   readium-desktop:main#services/lcp LSD {
[2]   readium-desktop:main#services/lcp   ID: '2277a638-5059-4bf3-b57a-27aba3b533e6',
[2]   readium-desktop:main#services/lcp   Status: 'returned',
[2]   readium-desktop:main#services/lcp   Message: 'The license is in returned state',
[2]   readium-desktop:main#services/lcp   Updated: Updated {
[2]   readium-desktop:main#services/lcp     License: 2024-05-01T17:47:16.000Z,
[2]   readium-desktop:main#services/lcp     Status: 2024-05-01T17:47:16.000Z
[2]   readium-desktop:main#services/lcp   },
[2]   readium-desktop:main#services/lcp   Links: [
[2]   readium-desktop:main#services/lcp     Link {
[2]   readium-desktop:main#services/lcp       Href: 'https://front-prod.edrlab.org/frontend/api/v1/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6',
[2]   readium-desktop:main#services/lcp       Type: 'application/vnd.readium.lcp.license.v1.0+json',
[2]   readium-desktop:main#services/lcp       Rel: 'license'
[2]   readium-desktop:main#services/lcp     }
[2]   readium-desktop:main#services/lcp   ],
[2]   readium-desktop:main#services/lcp   PotentialRights: PotentialRights { End: 2026-05-04T17:42:00.000Z },
[2]   readium-desktop:main#services/lcp   Events: [
[2]   readium-desktop:main#services/lcp     LsdEvent {
[2]   readium-desktop:main#services/lcp       Type: 'register',
[2]   readium-desktop:main#services/lcp       Name: 'Thorium',
[2]   readium-desktop:main#services/lcp       ID: '93933c79-79ba-4896-a6f5-b018f242915f',
[2]   readium-desktop:main#services/lcp       TimeStamp: 2024-05-01T17:42:51.000Z
[2]   readium-desktop:main#services/lcp     },
[2]   readium-desktop:main#services/lcp     LsdEvent {
[2]   readium-desktop:main#services/lcp       Type: 'return',
[2]   readium-desktop:main#services/lcp       Name: 'Thorium',
[2]   readium-desktop:main#services/lcp       ID: '93933c79-79ba-4896-a6f5-b018f242915f',
[2]   readium-desktop:main#services/lcp       TimeStamp: 2024-05-01T17:47:16.000Z
[2]   readium-desktop:main#services/lcp     }
[2]   readium-desktop:main#services/lcp   ]
[2]   readium-desktop:main#services/lcp } +689ms
```

relaunch `launchStatusDocumentProcessing`

```
[2]   readium-desktop:main#services/lsd Link Status FOUND:  Link {
[2]   Href: 'https://front-prod.edrlab.org/lsdserver/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6/status',
[2]   Type: 'application/vnd.readium.license.status.v1.0+json',
[2]   Rel: 'status'
[2] } +684ms
[2]   readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/lsdserver/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6/status +168ms
```

updating new lsd lisence
```
[2]   readium-desktop:main#services/lsd LSD license updating... +167ms
[2]   readium-desktop:main#services/lsd OLD LCP LICENSE, FETCHING LSD UPDATE ... https://front-prod.edrlab.org/frontend/api/v1/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6 +1ms
[2]   readium-desktop:main/http fetch URL: https://front-prod.edrlab.org/frontend/api/v1/licenses/2277a638-5059-4bf3-b57a-27aba3b533e6 +369ms
```

```
[2]   readium-desktop:main#services/lcp processStatusDocument LCP updated. +0ms
```

image

**Comment by danielweck** [comment]
great job LGTM!

**Pull request merged**
