### PR TITLE
fix #1087:

### LINKED ISSUE #1087: Thorium must be force-quit when CMD-W on library window, application remains alive with no windows (CMD-Q works fine)
```
  readium-desktop:main:saga:persist start of persist reduxState in disk +2s
  readium-desktop:main:saga:persist end of persist reduxState in disk +2ms
  readium-desktop:main:redux:sagas:win:session:library _______2 library.getBounds() { x: 305, y: 129, width: 800, height: 600 } +3s
  readium-desktop:sync ### action type WIN_SESSION_SET_BOUND +3s
  readium-desktop:sync ### action type WIN_PERSIST_REQUEST +0ms
  readium-desktop:main:saga:persist start of persist reduxState in disk +3s
  readium-desktop:main:saga:persist end of persist reduxState in disk +3ms
  readium-desktop:sync ### action type WIN_SESSION_UNREGISTER_LIBRARY +4s
  readium-desktop:sync ### action type WIN_PERSIST_REQUEST +0ms
  readium-desktop:sync ### action type LIBRARY_CLOSE_REQUEST +1ms
  readium-desktop:main:redux:sagas:win:library library -> winClose +6s
  readium-desktop:main:redux:sagas:win:library reader: [] +0ms
  readium-desktop:main:saga:app ##### +7s
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app window-all-closed +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:persist start of persist reduxState in disk +3s
  r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +7s
  r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
  r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +0ms
  r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +0ms
  readium-desktop:main:saga:persist end of persist reduxState in disk +11ms
  readium-desktop:sync ### action type STREAMER_STOP_REQUEST +65ms
  readium-desktop:sync ### action type STREAMER_STOP_SUCCESS +0ms
  readium-desktop:main:saga:persist start of persist reduxState in disk +938ms
  readium-desktop:main:saga:persist end of persist reduxState in disk +2ms
  readium-desktop:main:saga:app ##### +11s
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app shutdown +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +12s
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app shutdown +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +3s
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +1ms
  readium-desktop:main:saga:app shutdown +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +487ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app shutdown +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +400ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app shutdown +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +8s
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app before-quit +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
  readium-desktop:main:saga:app ##### +0ms
```

### PR DESCRIPTION
**Pull request by panaC**
- CMD-Q or Quit Thorium didn't work when there was no thorium windows on MAC-OS
    - add a MAC-OS condition to force close thorium
    - add a window menu with "show Library" to force the focus or to create the library window

### CODE REVIEW

**Comment by danielweck** [comment]
With `npm run start:dev`, closing the library window (with red cross icon or with CMD+W) causes the entire app to shut down, is this normal?
```
]   readium-desktop:main:redux:sagas:win:session:library _______2 library.getBounds() { x: 136, y: 74, width: 800, height: 600 } +4s
[2]   readium-desktop:sync ### action type WIN_SESSION_SET_BOUND +4s
[2]   readium-desktop:sync ### action type WIN_PERSIST_REQUEST +0ms
[2]   readium-desktop:main:saga:persist start of persist reduxState in disk +4s
[2]   readium-desktop:main:saga:persist end of persist reduxState in disk +4ms
[2]   readium-desktop:sync ### action type WIN_SESSION_UNREGISTER_LIBRARY +2s
[2]   readium-desktop:sync ### action type WIN_PERSIST_REQUEST +1ms
[2]   readium-desktop:sync ### action type LIBRARY_CLOSE_REQUEST +0ms
[2]   readium-desktop:main:redux:sagas:win:library library -> winClose +33s
[2]   readium-desktop:main:redux:sagas:win:library reader: [] +0ms
[2]   readium-desktop:main:saga:app ##### +39s
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app window-all-closed +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +1ms
[2]   readium-desktop:main:saga:persist start of persist reduxState in disk +1s
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +39s
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [persist:readium2pubwebview] => fulfilled +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +0ms
[2]   r2:navigator#electron/main/sessions SESSION CACHE + STORAGE DATA CLEARED - [default] => fulfilled +0ms
[2]   readium-desktop:main:saga:persist end of persist reduxState in disk +64ms
[2]   readium-desktop:sync ### action type STREAMER_STOP_REQUEST +120ms
[2]   readium-desktop:sync ### action type STREAMER_STOP_SUCCESS +2ms
[2]   readium-desktop:main:saga:app EXIT NOW +67ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app quit +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
[2]   readium-desktop:main:saga:app ##### +0ms
```

**Comment by danielweck** [comment]
I am merging this PR as-is, because it fixes an important bug. The `npm run start:dev` difference is not a big deal, because this is dev mode.

**Comment by panaC** [comment]
https://github.com/panaC/thorium/blob/c88c9f8d8c86a2191a1a49f698d958dc24321038/src/main/redux/sagas/app.ts#L81 ?

**Comment by danielweck** [comment]
thanks Pierre, i think we can now remove the dev special case, unless there is a problem specific to webpack dev server ( i don’t think so)

**Pull request merged**
