### PR TITLE
refactor(publication): migration PouchDB repository to main Redux state (PR #1415)

### PR DESCRIPTION
**Pull request by panaC**
follows https://github.com/edrlab/thorium-reader/commit/5630f255df7344fa11fcffcfe6c991d3c35f38cb and https://github.com/edrlab/thorium-reader/commit/1bc833ec2d766031c149ad3793a813abd9ea0e90

### CODE REVIEW

**Comment by panaC** [comment]
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/api/catalog.ts#L234

- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/api/lcp.ts#L38

- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/api/lcp.ts#L45
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/api/lcp.ts#L53
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/api/reader.ts#L76
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/api/reader.ts#L111
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/services/lcp.ts#L309
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/services/lcp.ts#L421
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/services/lcp.ts#L535

**Comment by panaC** [comment]
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/redux/sagas/api/publication/import/importFromFs.ts#L53
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/redux/sagas/api/publication/import/importLcplFromFs.ts#L127

**Comment by panaC** [comment]
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/redux/sagas/api/publication/findByTag.ts#L17

**Comment by panaC** [comment]
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/redux/sagas/api/publication/search.ts#L31

**Comment by panaC** [comment]
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/redux/sagas/api/publication/search.ts#L18

**Comment by panaC** [comment]
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/redux/sagas/api/publication/getAllTags.ts#L14

**Comment by panaC** [comment]
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/redux/sagas/api/publication/delete.ts#L30
- [ ] https://github.com/edrlab/thorium-reader/blob/1b41c006f0d6de28d02f78bb48ef3cbf2d12cae2/src/main/redux/sagas/api/publication/getPublication.ts#L22

**Comment by panaC** [comment]
it's works !

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/d69ae1f44e5a14549d951f5b523c613d71e0b43b/src/main/api/reader.ts#L66-L121

https://github.com/edrlab/thorium-reader/blob/d69ae1f44e5a14549d951f5b523c613d71e0b43b/src/main/db/document/publication.ts#L30 

add it in the redux state

**Comment by panaC** [comment]
remove pouchb find and search from package.json

**Comment by danielweck** [comment]
@panaC  this PR merge introduces a regression bug in the `develop` branch: PouchDB `find` plugin is still used (see for example `this.db.find()` https://github.com/edrlab/thorium-reader/blob/3b2c9c5a2babf908613dd54cbf819643c911f035/src/main/db/repository/base.ts#L149

I am taking care of this in the `lcp-secrets` refactor branch: https://github.com/edrlab/thorium-reader/tree/refactor/lcp-repo

**Pull request merged**
