### PR TITLE
fix css for opds publications 

### LINKED ISSUE #2375: opds publicationInfo LCP css spacing
image

### PR DESCRIPTION
**Pull request by arthur-lemeur**
Image

Fixes #2375

### CODE REVIEW

**Comment by arthur-lemeur** [comment]
Capture d’écran 2024-05-28 à 09 40 05

Fixes #2371

**Review by danielweck — CHANGES_REQUESTED** [review]
still quite a big left pad (gap)
see screenshot

**Comment by danielweck** [comment]
Screenshot 2024-05-29 at 12 30 29

**Comment by arthur-lemeur** [comment]
Capture d’écran 2024-05-29 à 13 15 00

This is a similar gap as the Figma model

**Comment by danielweck** [comment]
Thank you @arthur-lemeur I agree that the Figma design is authoritative, so I merged the PR. I think that the left-alignment looks good, but because the text is longer in real Thorium usage, there is a tiny right-hand-side gap and a large left-hand-side gap (=> wasted screen real estate, and imbalanced visuals).

**Pull request merged**
