### PR TITLE
[WIP] (NEEDS REVIEW) import with shift : start a routine to open - read - delete

### LINKED ISSUE #1119: Missing option to opt-out of bookshelf feature
For those who manually manage theirs eBooks themselves in a dedicated folder structure on their computer or in the cloud, their should be an option to opt-out of the bookshelf feature. As I opened a large number of ePubs to test the application, I saw the size of my hard disk decrease considerably. When I inspected the "C:\Users\%username%\AppData\Roaming\EDRLab.ThoriumReader" folder, I realised it nearly reached 1 GB! Fair enough, as I deleted the ePubs from the bookshelf, the size of the above folder decreased, but no one could seriously keep deleting every opened ePub when done reading it!

Why is it that so many ePub readers want to manage ebooks in users' stead? I think it all started with Calibre, but this is not a way to go. I believe it has to be optional.

### PR DESCRIPTION
**Pull request by panaC**
import with shift pressed : start a routine to open the reader, wait for it to close and then delete the publication

potentially fixes #1119

### CODE REVIEW

**Comment by danielweck** [comment]
```
Module not found: Error: Can't resolve 'websql' in '/home/runner/work/thorium-reader/thorium-reader/node_modules/pouchdb-adapter-node-websql/lib'
1352
     @ ./node_modules/pouchdb-adapter-node-websql/lib/index.es.js 3:0-28 7:12-18
```

**Comment by danielweck** [comment]
`./node_modules/pouchdb-adapter-node-websql/lib/index.es.js`:

`import websql from 'websql';`

```
import { assign } from 'pouchdb-utils';
import WebSqlPouchCore from 'pouchdb-adapter-websql-core';
import websql from 'websql';

function NodeWebSqlPouch(opts, callback) {
  var _opts = assign({
    websql: websql // pass node-websql in as our "openDatabase" function
  }, opts);

  WebSqlPouchCore.call(this, _opts, callback);
}

// overrides for normal WebSQL behavior in the browser
NodeWebSqlPouch.valid = function () {
  return true;
};
NodeWebSqlPouch.use_prefix = false; // no prefix necessary in Node

function index (PouchDB) {
  PouchDB.adapter('websql', NodeWebSqlPouch, true);
}

export default index;
```

**Comment by danielweck** [comment]
`./node_modules/pouchdb-adapter-node-websql/package.json`:

```
  "dependencies": {
    "pouchdb-adapter-websql-core": "7.0.0",
    "pouchdb-utils": "7.0.0",
    "websql": "1.0.0"
  },
```

**Comment by danielweck** [comment]
Looks like a GitHub Actions "cache" issue with the NPM dependencies, although I restarted the CI build ... to no avail. Not sure what is going on! :(

**Comment by danielweck** [comment]
Note that the non-ESModule index JS uses the exact same import, so I do not think that this is a WebPack-related issue.

`./node_modules/pouchdb-adapter-node-websql/lib/index.js`:

```
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var pouchdbUtils = require('pouchdb-utils');
var WebSqlPouchCore = _interopDefault(require('pouchdb-adapter-websql-core'));
var websql = _interopDefault(require('websql'));
```

**Comment by panaC** [comment]
what is the plan with this PR @danielweck @llemeurfr ?

**Review by danielweck — CHANGES_REQUESTED** [review]
Several merge conflicts to resolve.

@llemeurfr we will need to discuss whether this feature is a satisfactory solution for https://github.com/edrlab/thorium-reader/issues/1119

**Pull request closed without merging**
