### PR TITLE
new divina player integration

### LINKED ISSUE #1455: Divina; add an Audio ON button
A new feature of the Divina player is sound, synchronized with the images. 
But there is a limitation in Web browsers: the user must activate the sound before it can be played. Maybe we can overcome this in Thorium and activate the sound by default (as it is done for audiobooks), but whatever we can do, we need a button to mute the sound if the user does not want it. 

We can re-use the audio button at the top of the screen, already used for TTS and EPUB media-overlays. 

This button should appear only if the divina manifest contains at least one "sounds" array.

### LINKED ISSUE #1469: Divina: add a visual signal indicating the reading progression direction
The Divina player does not contain a visual signal indicating the reading progression direction, which can be ltr, rtl, ttb or even btt. 

Is it possible to add it at the level of the app, or should it be a Divina player evolution?

### PR DESCRIPTION
**Pull request by panaC**
fixes #1455
fixes #1469

### CODE REVIEW

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/edff799091a4b0081c232df377c6d27717f828ba/src/renderer/reader/components/Reader.tsx#L942-L960

**Comment by panaC** [comment]
'pagechange' event: 

image

**Comment by panaC** [comment]
I used this build : https://github.com/readium/divina-player-js/commit/8208ea321b485d2cd48998d3026a436dbcbc054d

reference this last master commit https://github.com/readium/divina-player-js/commit/e6497697eb5661bc9a4d17323aedaf1d29646263

**Comment by panaC** [comment]
Open a divina : 

from documentation: 
```
From a folder path (which should contain its Divina JSON as a manifest.json file): openDivinaFromFolderPath(folderPath, locator = null, options = null)
```

https://github.com/edrlab/thorium-reader/blob/0f6b71561c57381a5c693f297783a5ed7e6d013b/src/renderer/reader/components/Reader.tsx#L1103

- url : manifestUrl from streamer
- locator: the locator of the publication hydrated in reader
- options: 

https://github.com/edrlab/thorium-reader/blob/0f6b71561c57381a5c693f297783a5ed7e6d013b/src/renderer/reader/components/Reader.tsx#L1076-L1091

**Comment by panaC** [comment]
new Options : 

```
// Options for the Divina Player
const options = {
	//maxNbOfUnitsToLoadAfter: null, // Forcing null for this value will load all units
	initialNbOfResourcesToLoad: 1000,//null, // If 0 or null, the normal nb of initial resources will load
	allowsDestroy: true,
	allowsParallel: true,
	allowsZoomOnDoubleTap: true,
	allowsZoomOnCtrlOrAltScroll: true,
	allowsSwipe: true,
	allowsWheelScroll: true,
	allowsPaginatedScroll: true,
	isPaginationGridBased: true,
	isPaginationSticky: true,
	videoLoadTimeout: 2000,
};
```

**Comment by panaC** [comment]
events: 

https://github.com/edrlab/thorium-reader/blob/86b98512ace7a9a642c7eec7985665487f1341ca/src/renderer/reader/components/Reader.tsx#L1106-L1143

**Comment by panaC** [comment]
new Events : 

Here is the list of events, along with the data sent (in the form of an object):
- dataparsing: once the Divina JSON has been parsed and pageNavigatorsData created
Data: { readingProgression, readingModesArray, languagesArray }, where readingProgression can be used to position navigation controls, readingModesArray the list of all possible page navigators for the story, and languages the list of all possible languages for the story
- initialload: once the first batch of resources has been loaded
No data
- languagechange: once a language change has been validated
Data: { language }, where language is a BCP 47 tag
- readingmodechange: once a reading mode change has been validated (do note that, on opening a Divina, this event does happen after dataparsing)
Data: { readingMode, nbOfPages, hasSounds, isMuted }, where readingMode is “single” | “double” | “scroll” | “guided”, nbOfPages is that for the corresponding page navigator, hasShounds is a boolean that specifies whether the page navigator has sound animations, and isMuted a boolead that specified whether the player is currently muted or not) 
- readingmodesupdate: once the list of available reading modes has changed (in practice, the event only occurs if the double page reading mode becomes available or unavailable after a resize that forces a change from portrait to landscape mode or the opposite, only in the case where spread=”landscape”; if the double page reading mode stops to be available while it was the current reading mode, the single reading mode is forced)
Data: { readingModesArray, readingMode }, where reading mode is the (possibly forced) page navigator type (“single” | “double” | “scroll” | “guided”)
- pagechange: once a new page has been reached (if the page change involved a transition, the event only occurs once the transition has finished playing)
Data: { pageIndex, nbOfPages, locator }
- inpagescroll: on any progress change within an overflowing page
Data: { percent, locator }, where percent is the progress value within the page (between 0 and 1)

**Comment by panaC** [comment]
methods (from gdocs) : 

For changing reading settings:
setReadingMode(readingMode), where readingMode is a string that can take the following values (if available): “single” | “double” | “scroll” | “guided”
setLanguage(language), where the two letters have to correspond to the BCP 47 tag in link objects
setTag(tagName, tagValue)


For navigation:
goTo(href) - e.g. for a table of contents
goToPageWithIndex(pageIndex)
goRight()
goLeft()
goUp()
goDown()
goToMaxRight()
goToMaxLeft()
goToMaxUp()
goToMaxDown()
setPercentInPage(percent) - e.g. for a slider (percent = progress in page)
Note that there exists no goForward or goBackward!
For sounds:
mute()
unmute()

**Comment by panaC** [comment]
I note that the language in options is deprecated , should we set the language with `setLanguage` on initialization instead ?

**Comment by panaC** [comment]
new build https://github.com/readium/divina-player-js/commit/2eea3b7f0669a95f4ddf84a67abc56ccc0b389fe 2eea3b7f0669a95f4ddf84a67abc56ccc0b389fe

**Comment by panaC** [comment]
fixes #1455

**Comment by panaC** [comment]
current blocking point : the locator information is not applied at startup, why ?

**Comment by panaC** [comment]
new build https://github.com/readium/divina-player-js/commit/2e30f5884528015cc8989d166700a8a1669a3b8b 2e30f5884528015cc8989d166700a8a1669a3b8b

**Comment by panaC** [comment]
screenshot_2021-08-30_at_13 58 26

@danielweck do you have any idea why the divina cannot be loaded ? this commit may be the culprit : https://github.com/edrlab/thorium-reader/commit/cc85150b1b975aaceb8ce1f526d0489dfe7a8017

**Comment by danielweck** [comment]
Hello, I have just tested Thorium from the `develop` branch with `bravery-divina-v1.0.divina` and `webtoon-3.divina` ... everything seems to work fine.

**Comment by panaC** [comment]
new build https://github.com/readium/divina-player-js/commit/214912b754734a2c9c553f36a174014119a647d1 214912b754734a2c9c553f36a174014119a647d1

**Comment by panaC** [comment]
new build https://github.com/readium/divina-player-js/commit/4e1f859afb14b916923ec136af0284a72e22a990 4e1f859afb14b916923ec136af0284a72e22a990

**Review by danielweck — APPROVED** [review]
Code reviewed. PR Approved.

**Pull request merged**
