### PR TITLE
fixes #2270 annotation concurrent edit

### LINKED ISSUE #2270: annotations editor should be unique, no concurrent edits
follow-up to:
https://github.com/edrlab/thorium-reader/issues/2260

note that the keyboard shortcuts editor properly handles mouse-driven actuation of another editor (closes the current editor)

Screenshot 2024-05-20 at 15 02 33

### PR DESCRIPTION
**Pull request by panaC**
In docked mode I cannot apply a focus lock because there are too many mouse possible interaction in the header, focus lock is fighting then

Fixes #2270

### CODE REVIEW

**Comment by panaC** [comment]
add bookmarkList too

**Review by danielweck — CHANGES_REQUESTED** [review]
something is not right...sometimes when I click on the edit button the focus is redirected to the already opened editor, sometimes a new editor appears where I clicked. I test with or without any pending changes (e.g. inside text input area)

**Comment by danielweck** [comment]
I haven't tested the delete button yet, but we'll need to make sure that the state isn't corrupted when mixing edit/delete interactions.

**Comment by panaC** [comment]
> something is not right...sometimes when I click on the edit button the focus is redirected to the already opened editor, sometimes a new editor appears where I clicked. I test with or without any pending changes (e.g. inside text input area)

can you be more precise on your requesting change : 

On modal mode : focus-lock is applied, so when i click on edit the focus is redirected to textEdit, when i click on an another item, the focus is redirected to this item.
When I click on next/previous/delete(any) the item currently edited is closed

On docked mode: the focus-lock is disable (too many focus-fighting on search/annotation popover) the edition cannot be modal for me (need to discuss about that)
otherwise it's the same / the edited mode is close with next/previous/delete

**Comment by panaC** [comment]
> something is not right...sometimes when I click on the edit button the focus is redirected to the already opened editor, sometimes a new editor appears where I clicked. I test with or without any pending changes (e.g. inside text input area)

Got it , focusLock is broken, so I disabled it in this PR, and I filed an issue.

**Pull request merged**
