### PR TITLE
new command line -> open thorium with opds:// or multiple files at once

### LINKED ISSUE #1124: Trying to open (import) several EPUBs at once gives an error
From Windows File Explorer, selecting multiple EPUBs and pressing enter produces the following error message:

image

After clicking on [OK], Thorium successfully imports and opens _only_ the last EPUB of the entire set of selected EPUBs.

### LINKED ISSUE #1492: JavaScript Error while trying to open EPUB from another application
I was working on a literature review and decided to keep track of the various documents with a mind map using XMind. I figured it would be a neat idea to attach links to my PDFs and EPUBs to the various nodes of my mind map. I thought that when double clicking a link, it should open the attached file. Please note the file is not embedded; only a link to the full path of the file is saved with each node (another reason in favour of not storing EPUBs in your own DB repository). When I double click a link to a PDF, it opens in default PDF viewer without any problem. However, when I double click a link to an EPUB, bang!

image

If I click on OK, the book opens but there is an empty Thorium window behind it that opens too:

image

The EPUB is still readable. The only problem is the loud warning sound, the error message and the "ghost" Thorium window.

I tried creating a shortcut in Windows to the EPUB to see if I could reproduce the problem, but it just opened the EPUB without any error. I then tried creating a link to an EPUB in OneNote and it opened the same EPUB without any error. Why is it not working with XMind?

### LINKED ISSUE #1506: Create an easy way to add an OPDS feed to Thorium
Currently, the addition of an OPDs feed is tedious and for geeks only: one has to know the URL of an OPDS feed, copy/paste it, name it manually and validate. 

The new use case is: 
 - A user has a Readium-based app installed (desktop or mobile). 
 - A bookseller or public library adds a button to its website, labelled as "Add the catalog to your Readium app" (*) or equivalent.
 - The user clicks on the button provided on the website. 
 - The Readium app is triggered, catches the URL and name of the OPDS feed, automatically adds it to the list of feeds, opens the catalog.  

This can be achieved via what is called "OPDS callback", with a button attached to a URL of type `opds://`.

The same technique will be used in the scope of a OPDS "catalogs" feed, i.e. a list of OPDS feeds in which a user can choose one or more feeds to add to the app. See #1336. 

(*) I'm using the Readium brand here for marketing purpose. The scope could be wider  but - IMHO - non-Readium apps will hardly implement this.

### PR DESCRIPTION
**Pull request by panaC**
fixes #1506 
fixes #1124 

fixes #1492

### CODE REVIEW

**Comment by panaC** [comment]
image

**Comment by panaC** [comment]
image

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/44c5035a0ce92f4fc6fac1529b989162f091002b/src/main/cli/lock.ts#L107

on Windows : 'second-instance' event is called even if one instance is started !!

**Comment by panaC** [comment]
image

**Comment by panaC** [comment]
Ready to merge

Tested on Mac and Window

@danielweck I let you test on your side

you can check = opds:// in safari and edge web browser
you can check to open multiples ePub files with thorium already launched but library closed on Mac .. same on Windows

**Review by danielweck — APPROVED** [review]

**Comment by danielweck** [comment]
Minor follow-up bug: https://github.com/edrlab/thorium-reader/issues/1614

**Pull request merged**
