### PR TITLE
New PDF viewer

### LINKED ISSUE #1190: [PDF] 2 pages spread view
**currently  :**

image

this features doesn't works and isn't wired in the pdfReader https://github.com/edrlab/thorium-reader/blob/fa17ec90f5c15091f4b463a930a303610fd28dc4/src/renderer/reader/pdf/webview/pdfReader.ts#L482

**expected result :** 

image

'one' column is the default behaviour, one page view.
'auto' column can be mapped to the default behaviour or can be a smart view in function of the size of the window.

**how to fix it :**

update the rendering with one or more 'canvas'.
file: https://github.com/edrlab/thorium-reader/blob/fa17ec90f5c15091f4b463a930a303610fd28dc4/src/renderer/reader/pdf/webview/pdfReader.ts

PDF Pull Request : https://github.com/edrlab/thorium-reader/pull/1188

### LINKED ISSUE #1191: [PDF] scrolled or paginated view
**Currently :**

image

this features doesn't works and isn't wired in the pdfReader

https://github.com/edrlab/thorium-reader/blob/fa17ec90f5c15091f4b463a930a303610fd28dc4/src/renderer/reader/pdf/webview/pdfReader.ts#L474

**Expected result :**

image

- paginated : actual behaviour
- scrolled: canvas in succession (may be need a page cache to avoid rendering all pages once)

**how to fix it :**

update the rendering with one or more 'canvas'.
file: https://github.com/edrlab/thorium-reader/blob/fa17ec90f5c15091f4b463a930a303610fd28dc4/src/renderer/reader/pdf/webview/pdfReader.ts

PDF Pull Request : #1188

### LINKED ISSUE #1192: [PDF] pdf page scale (zoom) need to be more precise
**Currently :**

image

the zoom value isn't precise and need more steps.

**Expected result :**

the same behavior that the mozilla demo viewer https://mozilla.github.io/pdf.js/web/viewer.html

image

**how to fix it :**

file: https://github.com/edrlab/thorium-reader/blob/fa17ec90f5c15091f4b463a930a303610fd28dc4/src/renderer/reader/pdf/webview/pdfReader.ts

PDF Pull Request : #1188

@danielweck https://github.com/edrlab/thorium-reader/pull/1188#issuecomment-700834600

### LINKED ISSUE #1193: [PDF] improve annotation layer
https://github.com/edrlab/thorium-reader/blob/fa17ec90f5c15091f4b463a930a303610fd28dc4/src/renderer/reader/pdf/webview/pdfReader.ts#L384-L421

@danielweck https://github.com/edrlab/thorium-reader/pull/1188#issuecomment-700836083

### LINKED ISSUE #1194: [PDF] search
- search in pdfReader not mapped with pdfJs search api https://github.com/edrlab/thorium-reader/blob/fa17ec90f5c15091f4b463a930a303610fd28dc4/src/renderer/reader/pdf/webview/pdfReader.ts#L490

### LINKED ISSUE #1215: PDF pagination overflow counter: when reaching last page, continue to click "next" button, then observe that "previous" button must be clicked as many times to return into the page flow

### PR DESCRIPTION
**Pull request by panaC**
# New PDF Viewer

### **PDF LCP support** _DONE_ 

LCP protected PDF publication are treated like EPUB. The user passphrase is requested if needed.

If the PDF is protected by LCP, the copy/paste of text must either be limited by the rights in the license or (if this is not possible) prohibited.

### **PDF is detached from other file format** _DONE_
In the home screen, we find a “Resume reading PDF” section listing 5 (max) PDF documents read recently.

### **Generate a cover on import** _DONE_
PDF documents don’t contain a cover and Thorium must generate a cover on the fly at import time, from the first page of the publication. 

Note: check if using pdf.js for cover generation is better than using pdfium.
currently with pdfium it takes 7 seconds to capture the cover

### **Last reading position** _DONE_
The document is open on the last page the user has previously read, in page fit mode. 

### **Progression** _done_
The progression is displayed on the bottom of the screen, labelled via the title of the PDF document (later it will be related to the table of contents). 

### **Go to page** _done_
It is possible to go to a specific page by its page page “name” (“v” is avalid page number in some publications). The current page number is displayed, with the (English) label “Current page: x”.

### **Table of Contents** _done_
In the rare situation where a table of contents is available in the PDF (a PDF ToC is a nested list of labels and pdfjs locators), it is displayed. If not, a “no ToC” message is displayed.

### **Bookmarks** _done_
Bookmarks can be set on individual pages and indexed by their page number.

### **Search** _done_
The main difference between search in EPUB and search in PDF is that in the second case, search results are not displayed in the right panel as a paginated list. The user can only move from one result to the next/previous using arrow keys. 

Results are highlighted as in the EPUB case.  

### **Zoom** _done_
The Mozilla reader shows the multiple zoom options pdf.js is supporting. We’ll only implement a subset, i.e. the most logical actions for end-users. 

The zoom function is implemented in the right panel, with two discrete values - page fit and page width. 

The user can alse use “ctrl” (or “cmd” on a Mac) +/- or “ctrl” plus mouse scroll to adapt the zoom factor. 

Alternatively, zoom is available on touch screens via two-finger gestures.  

A page is scrollable if zoomed (vertically and horizontally).

If the user is in page width mode and uses the up/down arrows, he moves into the page vertically. He does not have to click on the page (to move focus on it) to get this behavior after moving to a new page (problem seen in the alpha version). On a Mac, “alt” plus up/down arrows move from segment to segment in a page. 

If the user is in page width mode and scrolls down (or uses the down arrow) to the bottom of the page, then insists in scrolling, the next page is displayed, from the top. Same behavior with scroll up to the top of the page. 

### **Page display** _done_ 
The user can set:

Layout :
- Scrollable
- Paginated

Columns:
- 1 col
- 2 cols

All combinations must work.

The Alignment segment (Automatic / Justify) one finds in the EPUB mode is not present in the PDF mode. 

Note: Display modes and zoom are independant properties, like in the Mozilla reader. 

## **How does it works** _diagrams_

fixes: 

fixes #1192 
fixes #1190 
fixes #1194 
fixes #1215
fixes #1193 
fixes #1191

### CODE REVIEW

**Review by danielweck — CHANGES_REQUESTED** [review]
I tried opening several PDF files but the reader window publication viewport remains blank. I see this in the console:

```
[2] (node:42662) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/..../dist/assets/lib/pdfjs/web/locale/locale.properties'
```

**Comment by danielweck** [comment]
I suggest that we revisit the "back button history" AFTER the PDF viewer is merged into the `develop` branch. https://github.com/edrlab/thorium-reader/pull/1200

**Comment by panaC** [comment]
> I tried opening several PDF files but the reader window publication viewport remains blank. I see this in the console:
> 
> ```
> [2] (node:42662) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/..../dist/assets/lib/pdfjs/web/locale/locale.properties'
> ```

I didn't see this error on my side.
I deleted several file from pdfjs-webviewer repositories. I will restore them.

**Comment by panaC** [comment]
> I tried opening several PDF files but the reader window publication viewport remains blank. I see this in the console:
> 
> ```
> [2] (node:42662) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/..../dist/assets/lib/pdfjs/web/locale/locale.properties'
> ```

`locale.propreties` is useless now, there are no pdfjs localization printed on the screen. I will investigate

**Comment by panaC** [comment]
> I tried opening several PDF files but the reader window publication viewport remains blank. I see this in the console:
> 
> ```
> [2] (node:42662) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/..../dist/assets/lib/pdfjs/web/locale/locale.properties'
> ```

fixed with https://github.com/edrlab/thorium-reader/pull/1285/commits/3974d3be22eeed6a529ca9a9d04ebe6dcc89c343

**Comment by danielweck** [comment]
Note to devs: https://github.com/edrlab/thorium-reader/issues/1004#issuecomment-758752644

**Comment by danielweck** [comment]
Still blank PDF viewport in reader window 
```
[2]   r2:navigator#electron/renderer/index_ pdf-webview _readPreferences: "Failed to read the 'localStorage' property from 'Window': Access is denied for this document.". +327ms
[2]   r2:navigator#electron/renderer/index_ pdf-webview no resource to load, early way out +1ms
```

**Review by danielweck — APPROVED** [review]

**Comment by danielweck** [comment]
TODO:
I think this Electron Builder "files" section should be removed, following the PDF viewer refactoring:
https://github.com/edrlab/thorium-reader/blob/0d9e15c745804c5815b0373adbac6f1b6081fa96/package.json#L129-L131

**Comment by danielweck** [comment]
See: https://github.com/edrlab/thorium-reader/issues/1317

**Pull request merged**
