### PR TITLE
fix(#2140): keep session message box at closing not preserved, annoying

### PR DESCRIPTION
**Pull request by panaC**

### CODE REVIEW

**Comment by danielweck** [comment]
Hello Pierre, I see your code comment that accompanies the code removal:

> // keep session in next startup disabled for the release of Thorium 3.0
> // session still exits between publication state but not saved at closing

Could you please clarify (sorry, I am confused, my fault not yours) what is a "session"? Does this mean that individual publications retain their own user preferences (e.g. font size, paginate vs. scroll etc.) during the application lifecycle, and Thorium automatically makes these settings persistent in the DB/JSON so that when the application is relaunched, all the publications keep their own preferences? What happens to a new publication that was never opened before?

**Comment by panaC** [comment]
> Hello Pierre, I see your code comment that accompanies the code removal:
> 
> > // keep session in next startup disabled for the release of Thorium 3.0
> > // session still exits between publication state but not saved at closing
> 
> Could you please clarify (sorry, I am confused, my fault not yours) what is a "session"? Does this mean that individual publications retain their own user preferences (e.g. font size, paginate vs. scroll etc.) during the application lifecycle, and Thorium automatically makes these settings persistent in the DB/JSON so that when the application is relaunched, all the publications keep their own preferences? What happens to a new publication that was never opened before?

I reply on the issue : https://github.com/edrlab/thorium-reader/issues/2140#issuecomment-2110222367

**Comment by danielweck** [comment]
@panaC So, instead of `value = messageValue.response;` could we pluck the boolean from global persistent application state (user-configurable preference, by default true = reader windows are restored automatically). No annoying confirmation dialog, the UX friction becomes minimal because users will just close their reader windows if they are annoyed by their re-appearance at next launch, or they will find the configuration checkbox or ask on the mailing list / GitHub :) (nobody reads the docs, sorry @gautierchomel ;)

**Comment by panaC** [comment]
I'm closing, replace by #2307

**Pull request closed without merging**
