### PR TITLE
[DAISY] Add application/zip mimetype

### PR DESCRIPTION
**Pull request by panaC**

### CODE REVIEW

**Comment by panaC** [comment]
failure on opdsControl when access on any publication with https://eole-recette.avh.asso.fr/api/v1/feed_eole

```
OpdsControls.tsx:27 Uncaught TypeError: Cannot read properties of undefined (reading 'indirectAcquisitionType')
    at OpdsControls.tsx:27:1
    at Array.sort (<anonymous>)
    at orderLinks (OpdsControls.tsx:26:1)
    at openAccessLinksButton (OpdsControls.tsx:43:1)
    at OpdsControls.render (OpdsControls.tsx:96:1)
    at finishClassComponent (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17485:31)
    at updateClassComponent (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17435:24)
    at beginWork (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
(anonymous) @ OpdsControls.tsx:27
orderLinks @ OpdsControls.tsx:26
openAccessLinksButton @ OpdsControls.tsx:43
render @ OpdsControls.tsx:96
finishClassComponent @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17485
updateClassComponent @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17435
beginWork @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:19073
callCallback @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:4056
beginWork$1 @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:23964
performUnitOfWork @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22776
workLoopSync @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22707
renderRootSync @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22670
performSyncWorkOnRoot @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22293
(anonymous) @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11309
discreteUpdates$1 @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22420
discreteUpdates @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3756
dispatchDiscreteEvent @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:5889
/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/r2-navigator-js/dist/es8-es2017/src/electron/renderer/common/console-redirect.js:74 The above error occurred in the <OpdsControls> component:

    at OpdsControls (http://localhost:8090/index_library.js:15760:9)
    at WrapperComponent (http://localhost:8090/index_library.js:12769:30)
    at ConnectFunction (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
    at div
    at div
    at PublicationInfoContent (http://localhost:8090/index_library.js:12491:13)
    at div
    at div
    at div
    at div
    at FocusLockUI (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-focus-lock/dist/cjs/Lock.js:40:31)
    at FocusLockUICombination
    at Dialog (http://localhost:8090/index_library.js:11825:9)
    at WrapperComponent (http://localhost:8090/index_library.js:12769:30)
    at PublicationInfoManager (http://localhost:8090/index_library.js:12576:13)
    at WrapperComponent (http://localhost:8090/index_library.js:12769:30)
    at PublicationInfo (http://localhost:8090/index_library.js:15350:9)
    at WrapperComponent (http://localhost:8090/index_library.js:12769:30)
    at ConnectFunction (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
    at DialogManager (http://localhost:8090/index_library.js:14801:9)
    at ConnectFunction (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
    at div
    at /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dropzone/dist/index.js:1:13327
    at Router (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-router/umd/react-router.development.js:821:17)
    at HistoryRouter (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/redux-first-history/rr6/index.js:11:22)
    at Provider (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-redux/lib/components/Provider.js:21:20)
    at App (http://localhost:8090/index_library.js:13386:9)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
newConsoleFunction @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/r2-navigator-js/dist/es8-es2017/src/electron/renderer/common/console-redirect.js:74
logCapturedError @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:20085
update.callback @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:20118
callCallback @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:12318
commitUpdateQueue @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:12339
commitLifeCycles @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:20736
commitLayoutEffects @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:23426
callCallback @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:4056
commitRootImpl @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:23151
unstable_runWithPriority @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11276
commitRoot @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22990
performSyncWorkOnRoot @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22329
(anonymous) @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11309
discreteUpdates$1 @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:22420
discreteUpdates @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3756
dispatchDiscreteEvent @ /sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:5889
/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:11340 Uncaught TypeError: Cannot read properties of undefined (reading 'indirectAcquisitionType')
    at OpdsControls.tsx:27:1
    at Array.sort (<anonymous>)
    at orderLinks (OpdsControls.tsx:26:1)
    at openAccessLinksButton (OpdsControls.tsx:43:1)
    at OpdsControls.render (OpdsControls.tsx:96:1)
    at finishClassComponent (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17485:31)
    at updateClassComponent (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:17435:24)
    at beginWork (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/sgoinfre/goinfre/Perso/pleroux/thorium-reader/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
```

**Comment by danielweck** [comment]
https://eole-recette.avh.asso.fr/api/v1/feed_eole

The import of `https://eole-recette.avh.asso.fr/api/v1/download/node/142675/field_filepath/0/1661524095?token=gXwEzFE_1JZa1pJUz2WyKMBe-wWX9x3mVIWZNZ_DH0k` failed. Error: fetch error `401 Unauthorized {"error":"Not Authorized"}`

**Comment by panaC** [comment]
> https://eole-recette.avh.asso.fr/api/v1/feed_eole
> 
> The import of `https://eole-recette.avh.asso.fr/api/v1/download/node/142675/field_filepath/0/1661524095?token=gXwEzFE_1JZa1pJUz2WyKMBe-wWX9x3mVIWZNZ_DH0k` failed. Error: fetch error `401 Unauthorized {"error":"Not Authorized"}`

fixed with #1801

**Review by danielweck — APPROVED** [review]
I do not have a OPDS feed that includes DAISY zip publications to test with ... but this looks good to me. Let's merge.

**Pull request merged**
