### PR TITLE
fix: Dialog modal

### LINKED ISSUE #1635: keyboard characters y and n for yes/no cannot be used to eg. delete a book form My Books?
I cannot use 'y' and 'n' for 'yes' and 'no'?
In My Books view -  I choose the action button next to the cover img and 'Delete'
image
The delete window now opens:
image
If I type 'y' now with my ordinary keyboard, I would think the file was deleted - but this doesn't happen. 
Instead keybord focus is activated and fixed on the close button, it seems. And I have to tab two times before focus sets on the 'yes' activation button and I can delete the file with enter.
Just an observation.

### PR DESCRIPTION
**Pull request by panaC**
fixes #1635

### CODE REVIEW

**Comment by panaC** [comment]
I added a new localisation key 'dialog.cancel' perhaps I should do re-used an old 'cancel' key instead

**Comment by danielweck** [comment]
bug:  keyboard activation of LCP hint hyperlink is broken (enter key only, not space unlike buttons).
I am working on a fix.

**Comment by danielweck** [comment]
bug: the "secondary" button style puts incorrect visual emphasis on button that is actually not the form / enter key default.
I am pushing a fix shortly.

**Comment by danielweck** [comment]
bug: the "API APP" dialog is completely broken with long result list, and the initial enter key form submit causes a crash in the console due to prematurely submitting via the dialog footer.
I am fixing this.

**Comment by danielweck** [comment]
bug: enter key submit bypasses sanity check of existing text in input fields (I am fixing this)

**Comment by danielweck** [comment]
bug: the opds feed editor allows empty text input field in one or the other (I am fixing this)

**Pull request merged**
